package main

import (
	"fmt"
	"os"
	"text/template"
)

type mapTo struct {
	Name   string
	GoType string
}

// nolint: funlen
func main() {
	templateDataBundle := []mapTo{
		// native types
		{Name: "Bool", GoType: "bool"},

		{Name: "Int", GoType: "int"},
		{Name: "Int8", GoType: "int8"},
		{Name: "Int16", GoType: "int16"},
		{Name: "Int32", GoType: "int32"},
		{Name: "Int64", GoType: "int64"},

		{Name: "Uint", GoType: "uint"},
		{Name: "Uint8", GoType: "uint8"},
		{Name: "Uint16", GoType: "uint16"},
		{Name: "Uint32", GoType: "uint32"},
		{Name: "Uint64", GoType: "uint64"},

		{Name: "Float32", GoType: "float32"},
		{Name: "Float64", GoType: "float64"},

		{Name: "Complex64", GoType: "complex128"},
		{Name: "Complex128", GoType: "complex128"},

		{Name: "String", GoType: "string"},
	}

	formatters := []mapTo{
		{
			Name:   "%s",
			GoType: "%s",
		},
		{
			Name:   "S%s",
			GoType: "[]%s",
		},
		{
			Name:   "%sPtr",
			GoType: "*%s",
		},
		{
			Name:   "S%sPtr",
			GoType: "[]*%s",
		},
	}

	file, err := os.Create(fmt.Sprintf("./mapto.go"))
	if err != nil {
		panic(err)
	}

	defer func() { _ = file.Close() }()

	_, _ = file.WriteString("// Code generated by maptoXXX.go DO NOT EDIT.\n")
	_, _ = file.WriteString("\npackage fuego\n")
	_, _ = file.WriteString("\n")

	for _, templateData := range templateDataBundle {
		for _, formatter := range formatters {
			adjustedTemplateData := mapTo{
				Name:   fmt.Sprintf(formatter.Name, templateData.Name),
				GoType: fmt.Sprintf(formatter.GoType, templateData.GoType),
			}

			mapToTmpl, err := template.ParseFiles("./generate/maptoXXX.go.tmpl")
			if err != nil {
				panic(err)
			}

			err = mapToTmpl.Execute(file, adjustedTemplateData)
			if err != nil {
				panic(err)
			}
		}
	}
}
